FROM ruphin/webserve

COPY ./src /usr/share/nginx/html
COPY ./node_modules/lit-html /usr/share/nginx/html/node_modules/lit-html
COPY ./node_modules/@gluon/gluon /usr/share/nginx/html/node_modules/@gluon/gluon
COPY ./node_modules/@gluon/router /usr/share/nginx/html/node_modules/@gluon/router
COPY ./node_modules/qrcode /usr/share/nginx/html/node_modules/qrcode
